apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: no-tls
  namespace: default
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80